//Usual
export const INITIAL_STATE = 'INITIAL_STATE';

//BookingsRequest
export const POST_BOOKINGREQUESTS_SUCCESS = 'POST_BOOKINGREQUESTS_SUCCESS';
export const POST_BOOKINGREQUESTS_UNSUCCESS = 'POST_BOOKINGREQUESTS_UNSUCCESS';
export const CLOSE_BOOKINGREQUEST_RESPONSE = 'CLOSE_BOOKINGREQUEST_RESPONSE';
export const ADD_BOOKINGREQUEST = 'ADD_BOOKINGREQUEST';
export const REMOVE_BOOKINGREQUEST = 'REMOVE_BOOKINGREQUEST';
export const UPDATE_BOOKINGREQUEST = 'UPDATE_BOOKINGREQUEST';
export const DELETE_BOOKINGREQUESTS_SUCCESS = 'DELETE_BOOKINGREQUESTS_SUCCESS';
export const DELETE_BOOKINGREQUESTS_UNSUCCESS = 'DELETE_BOOKINGREQUESTS_UNSUCCESS';

//DaySchedule
export const GET_DAYSCHEDULES_SUCCESS = 'GET_DAYSCHEDULES_SUCCESS';
export const GET_DAYSCHEDULES_UNSUCCESS = 'GET_DAYSCHEDULES_UNSUCCESS';
export const REMOVE_DAYSCHEDULES = 'REMOVE_DAYSCHEDULES';
export const CLOSE_DAYSCHEDULES_RESPONSE = 'CLOSE_DAYSCHEDULES_RESPONSE';

//ParameterSerch
export const UPDATE_PARAMETERS = 'UPDATE_PARAMETERS';
export const CLOSE_PARAMETERS_RESPONSE = 'CLOSE_PARAMETERS_RESPONSE';