//Usual
export const INITIAL_STATE = 'INITIAL_STATE';

//BookingsRequest
export const POST_BOOKINGREQUESTS_SUCCESS = 'POST_BOOKINGREQUESTS_SUCCESS';
export const POST_BOOKINGREQUESTS_UNSUCCESS = 'POST_BOOKINGREQUESTS_UNSUCCESS';
export const CLOSE_BOOKINGREQUEST_RESPONSE = 'CLOSE_BOOKINGREQUEST_RESPONSE';
export const ADD_BOOKINGREQUEST = 'ADD_BOOKINGREQUEST';
export const REMOVE_BOOKINGREQUEST = 'REMOVE_BOOKINGREQUEST';

